### ISSUE TITLE
error in response to Subscription::create

### ISSUE THREAD

**Issue by ghost** [rapiditynetworks/stripe-rust#13]
I'm getting a 'error converting between wire format and Rust types: invalid type: null, expected a string at line 34 column 26'. This was working previously. Stripe succeeds at creating the subscription and Stripe's body looks ok.

**Comment by ghost** [comment]
Sorry. The bug was on my side.

**Comment by kestred** [comment]
Ah sorry I haven't responded to this earlier.

Have you checked whether the null field is null-able according to the Stripe API?  
This type of error often occurs when I forgot to make a field `Option<_>` in the implementation.
