### ISSUE TITLE
Replace Option<&'static str> and Option<String> on enums for fields that can only contain specific values

### ISSUE THREAD

**Issue by ava57r** [rapiditynetworks/stripe-rust#19]
Example:
https://github.com/rapiditynetworks/stripe-rs/blob/master/src/resources/charge.rs#L190
valid value
`succeeded`, `pending`, or `failed`
https://stripe.com/docs/api#charge_object-status

Example2:
https://github.com/rapiditynetworks/stripe-rs/blob/master/src/resources/card.rs#L35
valid value
`pass`, `fail`, `unavailable`, or `unchecked`
https://stripe.com/docs/api#card_object-address_zip_check

Many types= )

**Comment by kestred** [comment]
I'm happy to accept a Pull Request for this issue!

I have re-created this issue in the new repository after the project moved orgs:
https://github.com/wyyerd/stripe-rs/issues/3.
