### ISSUE TITLE
[Question] Stripe v3 support?

### ISSUE THREAD

**Issue by rofrol** [rapiditynetworks/stripe-rust#7]
- Why no v3 support?
- Is it hard to implement?
- Is it needed?

**Comment by martell** [comment]
There is no such thing as a v3 api.
v3 is only for Stripe.js which is used in the browser / checkout form.
Versioning is managed from within the dashboard but all url's are post fixed with v1
https://stripe.com/docs/upgrades#api-changelog

**Comment by kestred** [comment]
Thanks for the clear response @martell.

@rofrol, as Martell is saying, the Stripe API has major version "v1" and that isn't going to change in the [foreseeable future](https://stripe.com/blog/api-versioning).

As such, the crate should be suitable for your purpose (I'll be happy to **implement** OR **accept PRs** for any Stripe requests you need which have yet to be implemented).

-------------

Given that the Stripe javascript libraries do reference similarly named major versions, I'll be sure to update the README and rust docs with the additional clarification.
