### ISSUE TITLE
Any rules on PR?

### ISSUE THREAD

**Issue by dariusc93** [rapiditynetworks/stripe-rust#8]
I would like to contribute back to this library (we made a stripe library for rust but we did use some parts from this library to complete some sections of our code during our rewrite) but would like to know if there is any specific formats, comments, etc., that is prefer before making a pr.

**Comment by kestred** [comment]
@dariusc93, sorry I missed this somehow.  Yes:

 - Minimize your changes to just the intended feature (no formatting/etc fixes).
 - Create one PR for each feature (or group of related features)

And generally follow best practices. See https://github.com/rapiditynetworks/stripe-rs/pull/6 for an example.
