### ISSUE TITLE
No support for `source` type in return from creating a charge

### ISSUE THREAD

**Issue by sindreij** [rapiditynetworks/stripe-rust#9]
I get this error when using a `Source` to create a `Charge`.

```
error converting between wire format and Rust types: unknown variant `source`, expected `card` at line 46 column 22
```

I think this is something that is not implented, and I'll try to create a PR.

**Comment by kestred** [comment]
@sindreij: Sound great.

I'll look into this tomorrow.
As you point out, I believe its caused by not yet supporting payment sources other than "Token" or "Card".

**Comment by sindreij** [comment]
Sounds correct. After creating this issue, I have found a few more things that needed to be implemented in this library. I have implemented the things I needed here: https://github.com/iterate/stripe-rs. My plan is to clean this up and create one or more PRs when I am finished with the payment implementation I am working on.

**Comment by kestred** [comment]
Implemented in https://github.com/wyyerd/stripe-rs/releases/tag/v0.5.0
